### ISSUE TITLE
gntagger panics when pointed at arbitrary file on OS X

### ISSUE THREAD

**Issue by mjy** [gnames/gntagger#20]
```
when I run gntagger on OS X 10.12.6 
   and I point it at an arbitrary text file (`file` returns `ASCII text`)
     then I get a panic
```

Dump:

```
matt@wireless taxonworks (loan_task $%)$ gntagger docker-compose.yml 

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gnames/gntagger.(*Text).Markup(0xc42007dbc0, 0xc420070840, 0x0, 0x0)
	/Users/dimus/go/src/github.com/gnames/gntagger/names.go:121 +0x5aa
github.com/gnames/gntagger.viewText(0xc420124870, 0xe8, 0x42, 0x0, 0x0)
	/Users/dimus/go/src/github.com/gnames/gntagger/gui.go:146 +0x19b
github.com/gnames/gntagger.Layout(0xc420124870, 0x0, 0x0)
	/Users/dimus/go/src/github.com/gnames/gntagger/gui.go:101 +0x80
github.com/jroimartin/gocui.ManagerFunc.Layout(0x18e37c0, 0xc420124870, 0x0, 0xc42b037ce8)
	/Users/dimus/go/src/github.com/jroimartin/gocui/gui.go:329 +0x30
github.com/jroimartin/gocui.(*Gui).flush(0xc420124870, 0x2, 0xc420124870)
	/Users/dimus/go/src/github.com/jroimartin/gocui/gui.go:435 +0xd9
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc420124870, 0x0, 0x0)
	/Users/dimus/go/src/github.com/jroimartin/gocui/gui.go:367 +0xb3
github.com/gnames/gntagger.InitGUI(0xc42007dbc0, 0xc420070840)
	/Users/dimus/go/src/github.com/gnames/gntagger/gui.go:34 +0x16a
main.main()
	/Users/dimus/go/src/github.com/gnames/gntagger/cmd/gntagger/main.go:43 +0x1dd
```

**Comment by mjy** [comment]
Probably the same as #18 ?

**Comment by dimus** [comment]
hm I guess I understood what it is. I did not try to run it with a file that has no scientific names

**Comment by dimus** [comment]
I will close this ticket and open a new one that explains the problem with docs without sci names more clearly

**Comment by dimus** [comment]
I made #21 and closing this one
