### ISSUE TITLE
gntagger on arbitrary text file panics (mac OS)

### ISSUE THREAD

**Issue by mjy** [gnames/gntagger#28]
when I run `gntagger .rspec`, and .rspec contains only `--color`, then I get a panic
```
gntagger .rspec
2017/11/08 10:05:25 mkdir : no such file or directory
panic: mkdir : no such file or directory

goroutine 1 [running]:
log.Panic(0xc420055d98, 0x1, 0x1)
	/usr/local/go/src/log/log.go:326 +0xc0
main.createFilesGently(0x0, 0x0, 0x13123dd, 0x9, 0xc420014550, 0x8, 0x8, 0xc420055ea8, 0x10c5ce0, 0xc42000e0c0, ...)
	/Users/dimus/go/src/github.com/gnames/gntagger/cmd/gntagger/main.go:98 +0x202
main.prepareData(0xc420116000, 0x8, 0x208, 0x7fff5fbff591, 0x6, 0x0, 0x0)
	/Users/dimus/go/src/github.com/gnames/gntagger/cmd/gntagger/main.go:69 +0xf6
main.main()
	/Users/dimus/go/src/github.com/gnames/gntagger/cmd/gntagger/main.go:53 +0x16d
```

**Comment by mjy** [comment]
In fact I get this on all text files right now.  I'm using the 1.1 tag.
